$('document').ready(function(){
    $('div').click(function(){
        $('div').fadeOut('fast');
    });
    $('div').hover(function(){
        $('div').addClass("red");
    });
    $('div').mouseleave(function(){
        $('div').removeClass("red");
    })
});
